name: Publish to gh-pages

on:
  repository_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.gitignore'
      - '.dockerignore'
      - 'README.md'
      - 'LICENSE'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # the Makefile is the source of truth
      - name: set docker image info from Makefile
        id: info
        shell: bash
        run: |
          set -x
          IMAGE_NAME=$(make print-image-name)
          IMAGE_VERSION=$(make print-image-version)
          echo "::set-output name=IMAGE_NAME::${IMAGE_NAME}"
          echo "::set-output name=IMAGE_VERSION::${IMAGE_VERSION}"

      - name: check info ok
        run: |
          IMAGE_NAME="${{ steps.info.outputs.IMAGE_NAME }}"
          printf 'IMAGE_NAME is: <<%s>>\n' "${IMAGE_NAME}"
          if [ -z ${IMAGE_NAME} ]; then
            false
          fi

          IMAGE_VERSION="${{ steps.info.outputs.IMAGE_VERSION }}"
          printf 'IMAGE_VERSION is: <<%s>>\n' "${IMAGE_VERSION}"
          if [ -z ${IMAGE_VERSION} ]; then
            false
          fi

      - name: Log in to github Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # not sure this is actually needed
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: debug - dump metadata
        shell: bash
        run: |
          printf 'tags are: <<%s>>\n' "${{ steps.meta.outputs.tags }}"
          printf 'tags labels are: <<%s>>\n' "${{ steps.meta.outputs.labels }}"
          printf 'repos is: <<%s>>\n' "${{ github.repository }}"

      # really, this is just using info that _mostly_
      # could've been got from makefile.
      # But some is from CI environment.
      - name: Build Docker image
        shell: bash
        run: |
          set -x

          export IMAGE_NAME="${{ steps.info.outputs.IMAGE_NAME }}"
          export GH_IMAGE_ID="${{ env.REGISTRY }}/${{ github.repository }}/${{ steps.info.outputs.IMAGE_NAME }}"
          export IMAGE_VERSION="${{ steps.info.outputs.IMAGE_VERSION }}"
          export REPO_OWNER="${{ github.repository_owner }}"

          echo "${{ steps.meta.outputs.labels }}" > oc_labels
          # "

          python3 ./build.py

    #- name: Use Node.js
    #  uses: actions/setup-node@v1
    #  with:
    #    node-version: '12.x'

    #- run: yarn
    #- run: yarn run build

    #- name: Deploy
    #  uses: peaceiris/actions-gh-pages@v3
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
    #    publish_dir: ./build


